### ISSUE TITLE
[Bug]: Combine enchanted books in Anvil

### ISSUE THREAD

**Issue by ErythroCraft** [zivoric/ZEnchantmentCore#21]
Hello

Player can not combine enchanted books.
Server console generated bug see below.

Core plugin: ZEnchantmentCore v2.1.1
Basic plugin: ZEnchantments-Basic v1.4.0
Server: 3482-Spigot-42b6152-e87f2e3 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT)

    [11:53:43] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return                 
    value of "java.lang.reflect.Method.invoke(Object, Object[])" is null
    [11:53:43] [Server thread/WARN]: 	at io.zivoric.enchantmentcore.utils.EnchantmentUtils.getAnvilCost(EnchantmentUtils.java:369)
    [11:53:43] [Server thread/WARN]: 	at io.zivoric.enchantmentcore.ItemEnchantListener.onAnvil(ItemEnchantListener.java:94)
    [11:53:43] [Server thread/WARN]: 	at jdk.internal.reflect.GeneratedMethodAccessor1177.invoke(Unknown Source)
    [11:53:43] [Server thread/WARN]: 	at 
    java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [11:53:43] [Server thread/WARN]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    [11:53:43] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
    [11:53:43] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
    [11:53:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589)
    [11:53:43] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576)
    [11:53:43] [Server thread/WARN]: 	at 
    org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPrepareAnvilEvent(CraftEventFactory.java:1484)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.ContainerAnvil.l(ContainerAnvil.java:286)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.ContainerAnvilAbstract.a(ContainerAnvilAbstract.java:80)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.ContainerAnvilAbstract$1.e(ContainerAnvilAbstract.java:25)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.Slot.d(SourceFile:66)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.Slot.d(SourceFile:62)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.Container.a(Container.java:824)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.ContainerAnvilAbstract.b(ContainerAnvilAbstract.java:124)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.Container.b(Container.java:534)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.world.inventory.Container.a(Container.java:377)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:2470)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:58)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.network.protocol.game.PacketPlayInWindowClick.a(SourceFile:13)
    [11:53:43] [Server thread/WARN]: 	at 
    net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.TickTask.run(SourceFile:18)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1190)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.y(SourceFile:131)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1169)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1162)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.util.thread.IAsyncTaskHandler.bo(SourceFile:116)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1145)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1051)
    [11:53:43] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304)
    [11:53:43] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by ErythroCraft** [comment]
An other plugin was fixing it.
